name: Release
on:
  push:
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install packages
        run: sudo apt-get install dpkg-dev rpm gzip git gnupg rsync jq
      - name: Import signing key
        run: echo "${GPG_KEY}" | base64 -d | gpg --batch --import
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - name: Run release
        run: ./scripts/build.sh
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
